/*
 * Funzioni_operatore.h
 *
 *  Created on: 26 giu 2021
 *      Author: Gabriele
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
#include <unistd.h>
#include "Strutture.h"
#include "Algoritmi_fondamentali.h"

#ifndef FUNZIONI_OPERATORE_H_
#define FUNZIONI_OPERATORE_H_

void inserimento_prodotti (FILE* file_prod);

/*
 *  LA PROCEDURA INSERIMENTO PRODOTTI RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "PRODOTTI.dat",
 *  E PERMETTE DI CARICARE UN NUOVO PRODOTTO ATTRAVERSO L'INSERIMENTO DI TUTTI I DATI NECESSARI
 *  OPPURE PERMETTE DI MODIFICARE LA QUANTITA' DISPONIBILE DI UN PRODOTTO
 */

void statistica_citta (FILE* file_ord);

/*
 *  LA PROCEDURA STATISTICA CITTA' RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "ORDINI.dat",
 *  E CALCOLA E VISUALIZZA IN ORDINI LE CITTA' CON MAGGIORI ORDINI EFFETTUATI
 */

void statistica_prezzo (FILE* file_ord);

/*
 *  LA PROCEDURA STATISTICA PREZZO RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "ORDINI.dat",
 *  E CALCOLA E VISUALIZZA I 5 ORDINI PIU' COSTOSI EFFETTUATI
 */

void statistica_quantita_vendute (FILE* file_prod);

/*
 *  LA PROCEDURA STATISTICA PREZZO RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "PRODOTTI.dat",
 *  E CALCOLA E VISUALIZZA I 5 PRODOTTI PIU' VENDUTI
 */

void statistica_quantita_ordini (FILE* file_ord);

/*
 *  LA PROCEDURA STATISTICA QUANTITA' ORDINI RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "ORDINI.dat",
 *  E CALCOLA E VISUALIZZA I 5 ORDINI EFFETTUATI CON MAGGIOR NUMERO DI PEZZI
 */

void ricerca_e_gestione_ordine (FILE* file_ord);

/*
 *  LA PROCEDURA RICERCA E GESTIONE ORDINE RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "ORDINI.dat",
 *  PERMETTE ALL'UTENTE DI POTER VISUALIZZARE GLI ORDINI APERTI ( stato = "da_consegnare" o "in_transito" ),
 *  GLI ORDINI CHIUSI ( stato = "conegnato" ) E DI MODIFICARE GLI ORDINI APERTI ATTRAVERSO UNA CHIAMATA
 *  ALLA FUNZIONE MODIFICA ORDINI APERTI
 */

void modifica_ordini_aperti (FILE* file_ord);

/*
 *  LA PROCEDURA STATISTICA QUANTITA' ORDINI RICHIEDE COME PARAMETRO IL PUNTATORE AI FILE "ORDINI.dat",
 * 	PERMETTE DI MODIFICARE LO STATO DI UN ORDINE RICERCATO ATTRAVERSO UNA RICERCA PER NOME PRODOTTO
 */

#endif /* FUNZIONI_OPERATORE_H_ */
