/*
 * Menu.h
 *
 *  Created on: 26 giu 2021
 *      Author: Gabriele
 */

#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "Strutture.h"
#include "Funzioni_operatore.h"


#ifndef MENU_H_
#define MENU_H_

int menu_gen ();

/*
 *  LA FUNZIONE MENU GEN PERMETTE LA VISUALIZZAZIONE DEL MEU GENERALE
 *  E LA SELEZIONE DELLA MODALITA' DI ACCESSO, RESTITUISCE LA SCELTA EFFETTUATA DALL'UTENTE
 */

int menu_op ();

/*
 *  LA FUNZIONE MENU OP PERMETTE LA VISUALIZZAZIONE DEL MENU OPERATORE E LA SELEZIONE
 *  DELL'OPERAZIONE DA COMPIERE, RESTITUISCE LA SCELTA EFFETTUATA DALL'OPERATORE
 */

int menu_cli ();

/*
 *  LA FUNZIONE MENU CLI PERMETTE LA VISUALIZZAZIONE DEL MENU CLIENTE E LA SELEZIONE
 *  DELL'OPERAZIONE DA COMPIERE, RESTITUISCE LA SCELTA EFFETTUATA DAL CLIENTE
 */

void menu_statistica (FILE* file_prod, FILE* file_ord);

/*
 *  LA FUNZIONE MENU STATISTICA PERMETTE LA VISUALIZZAZIONE DEL MENU STATISTICA E LA SELEZIONE
 *  DELLA STATISTICA CHE SI VUOLE VISUALIZZARE, RESTITUISCE LA SCELTA EFFETTUATA DALL'OPERATORE
 */

void lato_op ();

/*
 *  LA FUNZIONE LATO OPERATORE PERMETTE ALL'UTENTE DI INSERIRE LA PASSWORD PER ACCEDERE
 *  AL MENU OPERATORE E NE EFFETTUA IL CONTROLLO
 */

#endif /* MENU_H_ */
